# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import payment_gateway_pb2 as payment__gateway__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payment_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterBank = channel.unary_unary(
                '/PaymentGateway/RegisterBank',
                request_serializer=payment__gateway__pb2.RegisterBankRequest.SerializeToString,
                response_deserializer=payment__gateway__pb2.RegisterBankResponse.FromString,
                _registered_method=True)
        self.AuthenticateClient = channel.unary_unary(
                '/PaymentGateway/AuthenticateClient',
                request_serializer=payment__gateway__pb2.AuthRequest.SerializeToString,
                response_deserializer=payment__gateway__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.CheckBalance = channel.unary_unary(
                '/PaymentGateway/CheckBalance',
                request_serializer=payment__gateway__pb2.BalanceRequest.SerializeToString,
                response_deserializer=payment__gateway__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.ProcessPayment = channel.unary_unary(
                '/PaymentGateway/ProcessPayment',
                request_serializer=payment__gateway__pb2.PaymentRequest.SerializeToString,
                response_deserializer=payment__gateway__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.ViewTransactionHistory = channel.unary_unary(
                '/PaymentGateway/ViewTransactionHistory',
                request_serializer=payment__gateway__pb2.TransactionHistoryRequest.SerializeToString,
                response_deserializer=payment__gateway__pb2.TransactionHistoryResponse.FromString,
                _registered_method=True)
        self.LogoutClient = channel.unary_unary(
                '/PaymentGateway/LogoutClient',
                request_serializer=payment__gateway__pb2.LogoutRequest.SerializeToString,
                response_deserializer=payment__gateway__pb2.LogoutResponse.FromString,
                _registered_method=True)


class PaymentGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterBank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthenticateClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewTransactionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterBank': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterBank,
                    request_deserializer=payment__gateway__pb2.RegisterBankRequest.FromString,
                    response_serializer=payment__gateway__pb2.RegisterBankResponse.SerializeToString,
            ),
            'AuthenticateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateClient,
                    request_deserializer=payment__gateway__pb2.AuthRequest.FromString,
                    response_serializer=payment__gateway__pb2.AuthResponse.SerializeToString,
            ),
            'CheckBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBalance,
                    request_deserializer=payment__gateway__pb2.BalanceRequest.FromString,
                    response_serializer=payment__gateway__pb2.BalanceResponse.SerializeToString,
            ),
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=payment__gateway__pb2.PaymentRequest.FromString,
                    response_serializer=payment__gateway__pb2.PaymentResponse.SerializeToString,
            ),
            'ViewTransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewTransactionHistory,
                    request_deserializer=payment__gateway__pb2.TransactionHistoryRequest.FromString,
                    response_serializer=payment__gateway__pb2.TransactionHistoryResponse.SerializeToString,
            ),
            'LogoutClient': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutClient,
                    request_deserializer=payment__gateway__pb2.LogoutRequest.FromString,
                    response_serializer=payment__gateway__pb2.LogoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PaymentGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PaymentGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterBank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentGateway/RegisterBank',
            payment__gateway__pb2.RegisterBankRequest.SerializeToString,
            payment__gateway__pb2.RegisterBankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthenticateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentGateway/AuthenticateClient',
            payment__gateway__pb2.AuthRequest.SerializeToString,
            payment__gateway__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentGateway/CheckBalance',
            payment__gateway__pb2.BalanceRequest.SerializeToString,
            payment__gateway__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentGateway/ProcessPayment',
            payment__gateway__pb2.PaymentRequest.SerializeToString,
            payment__gateway__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewTransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentGateway/ViewTransactionHistory',
            payment__gateway__pb2.TransactionHistoryRequest.SerializeToString,
            payment__gateway__pb2.TransactionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogoutClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentGateway/LogoutClient',
            payment__gateway__pb2.LogoutRequest.SerializeToString,
            payment__gateway__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
