# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment_gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment_gateway.proto\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"E\n\x0c\x41uthResponse\x12\x15\n\rauthenticated\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"#\n\x0e\x42\x61lanceRequest\x12\x11\n\tbank_name\x18\x01 \x01(\t\"\"\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x01\"\x89\x01\n\x0ePaymentRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x18\n\x10sender_bank_name\x18\x02 \x01(\t\x12\x19\n\x11receiver_username\x18\x03 \x01(\t\x12\x1a\n\x12receiver_bank_name\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x01\"K\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\"\x0f\n\rLogoutRequest\"2\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\x19TransactionHistoryRequest\"\xbf\x01\n\x0bTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x11\n\tfrom_bank\x18\x02 \x01(\t\x12\x0f\n\x07to_bank\x18\x03 \x01(\t\x12\x17\n\x0f\x66rom_account_no\x18\x04 \x01(\t\x12\x14\n\x0c\x66rom_user_id\x18\x05 \x01(\t\x12\x12\n\nto_user_id\x18\x06 \x01(\t\x12\x0e\n\x06\x61mount\x18\x07 \x01(\x01\x12\x11\n\ttimestamp\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\"@\n\x1aTransactionHistoryResponse\x12\"\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x0c.Transaction2\xaf\x02\n\x0ePaymentGateway\x12\x31\n\x12\x41uthenticateClient\x12\x0c.AuthRequest\x1a\r.AuthResponse\x12\x31\n\x0c\x43heckBalance\x12\x0f.BalanceRequest\x1a\x10.BalanceResponse\x12\x33\n\x0eProcessPayment\x12\x0f.PaymentRequest\x1a\x10.PaymentResponse\x12Q\n\x16ViewTransactionHistory\x12\x1a.TransactionHistoryRequest\x1a\x1b.TransactionHistoryResponse\x12/\n\x0cLogoutClient\x12\x0e.LogoutRequest\x1a\x0f.LogoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=25
  _globals['_AUTHREQUEST']._serialized_end=74
  _globals['_AUTHRESPONSE']._serialized_start=76
  _globals['_AUTHRESPONSE']._serialized_end=145
  _globals['_BALANCEREQUEST']._serialized_start=147
  _globals['_BALANCEREQUEST']._serialized_end=182
  _globals['_BALANCERESPONSE']._serialized_start=184
  _globals['_BALANCERESPONSE']._serialized_end=218
  _globals['_PAYMENTREQUEST']._serialized_start=221
  _globals['_PAYMENTREQUEST']._serialized_end=358
  _globals['_PAYMENTRESPONSE']._serialized_start=360
  _globals['_PAYMENTRESPONSE']._serialized_end=435
  _globals['_LOGOUTREQUEST']._serialized_start=437
  _globals['_LOGOUTREQUEST']._serialized_end=452
  _globals['_LOGOUTRESPONSE']._serialized_start=454
  _globals['_LOGOUTRESPONSE']._serialized_end=504
  _globals['_TRANSACTIONHISTORYREQUEST']._serialized_start=506
  _globals['_TRANSACTIONHISTORYREQUEST']._serialized_end=533
  _globals['_TRANSACTION']._serialized_start=536
  _globals['_TRANSACTION']._serialized_end=727
  _globals['_TRANSACTIONHISTORYRESPONSE']._serialized_start=729
  _globals['_TRANSACTIONHISTORYRESPONSE']._serialized_end=793
  _globals['_PAYMENTGATEWAY']._serialized_start=796
  _globals['_PAYMENTGATEWAY']._serialized_end=1099
# @@protoc_insertion_point(module_scope)
