# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment_gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment_gateway.proto\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"4\n\x0c\x41uthResponse\x12\x15\n\rauthenticated\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\"\x10\n\x0e\x42\x61lanceRequest\"\"\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x01\"4\n\x0ePaymentRequest\x12\x12\n\nto_account\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"3\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xab\x01\n\x0ePaymentGateway\x12\x31\n\x12\x41uthenticateClient\x12\x0c.AuthRequest\x1a\r.AuthResponse\x12\x31\n\x0c\x43heckBalance\x12\x0f.BalanceRequest\x1a\x10.BalanceResponse\x12\x33\n\x0eProcessPayment\x12\x0f.PaymentRequest\x1a\x10.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=25
  _globals['_AUTHREQUEST']._serialized_end=74
  _globals['_AUTHRESPONSE']._serialized_start=76
  _globals['_AUTHRESPONSE']._serialized_end=128
  _globals['_BALANCEREQUEST']._serialized_start=130
  _globals['_BALANCEREQUEST']._serialized_end=146
  _globals['_BALANCERESPONSE']._serialized_start=148
  _globals['_BALANCERESPONSE']._serialized_end=182
  _globals['_PAYMENTREQUEST']._serialized_start=184
  _globals['_PAYMENTREQUEST']._serialized_end=236
  _globals['_PAYMENTRESPONSE']._serialized_start=238
  _globals['_PAYMENTRESPONSE']._serialized_end=289
  _globals['_PAYMENTGATEWAY']._serialized_start=292
  _globals['_PAYMENTGATEWAY']._serialized_end=463
# @@protoc_insertion_point(module_scope)
